In [100]:
import pandas as pd
import numpy as np
import comtrade
import os

In [101]:
features = {'U | BusBar-1 | phase: A',
            'U | BusBar-1 | phase: B',
            'U | BusBar-1 | phase: C',
            'U | BusBar-1 | phase: N',          
            'U | BusBar-1 | phase: AB',
            'U | BusBar-1 | phase: BC',
            'U | BusBar-1 | phase: CA',

            'U | CableLine-1 | phase: A',
            'U | CableLine-1 | phase: B',
            'U | CableLine-1 | phase: C',
            'U | CableLine-1 | phase: N',         
            'U | CableLine-1 | phase: AB',
            'U | CableLine-1 | phase: BC',
            'U | CableLine-1 | phase: CA',

            'I | Bus-1 | phase: A',
            'I | Bus-1 | phase: B',
            'I | Bus-1 | phase: C',
            
            'I | Bus-1 | phase: N',

            'U | BusBar-2 | phase: A',
            'U | BusBar-2 | phase: B',
            'U | BusBar-2 | phase: C',
            'U | BusBar-2 | phase: N',
            'U | BusBar-2 | phase: AB',
            'U | BusBar-2 | phase: BC',
            'U | BusBar-2 | phase: CA',

            'U | CableLine-2 | phase: A',
            'U | CableLine-2 | phase: B',
            'U | CableLine-2 | phase: C',
            'U | CableLine-2 | phase: N',
            'U | CableLine-2 | phase: AB',
            'U | CableLine-2 | phase: BC',
            'U | CableLine-2 | phase: CA',

            'I | Bus-2 | phase: A',
            'I | Bus-2 | phase: B',
            'I | Bus-2 | phase: C',
            
            'I | Bus-2 | phase: N',

            'U | BusBar-3 | phase: A',
            'U | BusBar-3 | phase: B',
            'U | BusBar-3 | phase: C',
            'U | BusBar-3 | phase: N',

            'I | Bus-3 | phase: A',
            'I | Bus-3 | phase: B',
            'I | Bus-3 | phase: C',
            
            'I | Bus-3 | phase: N',

            'U | CableLine-3 | phase: CA',

            'U | BusBar-4 | phase: A',
            'U | BusBar-4 | phase: B',
            'U | BusBar-4 | phase: C',

            'I | Bus-4 | phase: A',
            'I | Bus-4 | phase: B',
            'I | Bus-4 | phase: C',
            
            'I | Bus-4 | phase: N',

            'I | Bus-5 | phase: A',
            'I | Bus-5 | phase: B',
            'I | Bus-5 | phase: C',
            
            'I | Bus-5 | phase: N',

            'I | Bus-6 | phase: A',
            'I | Bus-6 | phase: B',
            'I | Bus-6 | phase: C',
            
            'I | Bus-6 | phase: N',

            'I | dif-1 | phase: A',
            'I | dif-1 | phase: B',
            'I | dif-1 | phase: C',

            'I | braking-1 | phase: A',
            'I | braking-1 | phase: B',
            'I | braking-1 | phase: C',

            'U_raw | CableLine-1 | phase: A',
            'U_raw | CableLine-1 | phase: B',
            'U_raw | CableLine-1 | phase: C',

            'I_raw | Bus-1 | phase: A',
            'I_raw | Bus-1 | phase: B',
            'I_raw | Bus-1 | phase: C',

            'U_raw | CableLine-2 | phase: A',
            'U_raw | CableLine-2 | phase: B',
            'U_raw | CableLine-2 | phase: C',

            'I_raw | Bus-2 | phase: A',
            'I_raw | Bus-2 | phase: B',
            'I_raw | Bus-2 | phase: C'
           }

In [145]:
window_size = 32
df = comtrade.load_as_dataframe('../../datasets/pqd/raw/f_network = 50 and f_rate = 1600/fadbee0c048d5df0f0e49478a929f5a1.cfg')
df.head()

I | Bus-1 | phase: A  I | Bus-1 | phase: B  I | Bus-1 | phase: C  \
time                                                                         
0.000000              1.814419             -0.011169           -258.969055   
0.000625             94.379097             -0.011169             -0.011496   
0.001250           -295.387756           -205.765198            199.992859   
0.001875             17.249544             -0.029567             -0.020706   
0.002500             31.293203             -0.011169             -0.011496   

          U | BusBar-1 | phase: A  U | BusBar-1 | phase: B  \
time                                                         
0.000000                -0.004381                 0.000359   
0.000625              -467.079742              -502.512817   
0.001250                64.714722              -254.557846   
0.001875                -0.004381                 0.000359   
0.002500              -464.078583                22.948507   

          U | BusBar-1 | phase: C  U | BusBar-1 | phase: N  \
time                                                         
0.000000                -0.016754              -278.020630   
0.000625                22.166101                -0.014154   
0.001250                -0.016754                -0.014154   
0.001875               211.078171                -0.014154   
0.002500                25.215078                -0.014154   

          U | CableLine-1 | phase: A  U | CableLine-1 | phase: B  \
time                                                               
0.000000                  159.385773                  255.651764   
0.000625                   37.823685                 -370.099426   
0.001250                   -0.007031                 -498.766418   
0.001875                   20.206669                   -0.003105   
0.002500                   -0.022580                    7.972506   

          U | CableLine-1 | phase: C  ...  Сраб. по углу 2ст 1СШ  \
time                                  ...                          
0.000000                   -0.017582  ...                      1   
0.000625                 -328.524750  ...                      0   
0.001250                 -350.321503  ...                      0   
0.001875                   10.468510  ...                      1   
0.002500                   63.739101  ...                      0   

          Разрешение работы 2ст 2СШ  Сраб. по углу 2ст 2СШ  Блокировка 3ст  \
time                                                                         
0.000000                          1                      0               1   
0.000625                          1                      0               1   
0.001250                          1                      1               1   
0.001875                          1                      1               1   
0.002500                          1                      0               1   

          Разрешение работы 3ст 1СШ  Сраб. по углу 3ст 1СШ  \
time                                                         
0.000000                          0                      0   
0.000625                          1                      1   
0.001250                          0                      1   
0.001875                          0                      0   
0.002500                          0                      1   

          Разрешение работы 3ст 2СШ  Сраб. по углу 3ст 2СШ  \
time                                                         
0.000000                          0                      0   
0.000625                          0                      0   
0.001250                          0                      0   
0.001875                          1                      0   
0.002500                          1                      0   

          PDR | Bus-1 | phase: PS  PDR | Bus-2 | phase: PS  
time                                                        
0.000000                        1                        1  
0.000625                        1      

In [146]:
df.columns

Index(['I | Bus-1 | phase: A', 'I | Bus-1 | phase: B', 'I | Bus-1 | phase: C',
       'U | BusBar-1 | phase: A', 'U | BusBar-1 | phase: B',
       'U | BusBar-1 | phase: C', 'U | BusBar-1 | phase: N',
       'U | CableLine-1 | phase: A', 'U | CableLine-1 | phase: B',
       'U | CableLine-1 | phase: C',
       ...
       'Сраб. по углу 2ст 1СШ', 'Разрешение работы 2ст 2СШ',
       'Сраб. по углу 2ст 2СШ', 'Блокировка 3ст', 'Разрешение работы 3ст 1СШ',
       'Сраб. по углу 3ст 1СШ', 'Разрешение работы 3ст 2СШ',
       'Сраб. по углу 3ст 2СШ', 'PDR | Bus-1 | phase: PS',
       'PDR | Bus-2 | phase: PS'],
      dtype='object', length=140)

In [147]:
osc_columns = df.columns
osc_features = []
to_drop = []
for column in osc_columns:
    if column in features:
        osc_features.append(column)
    else:
        to_drop.append(column)
df.drop(columns=to_drop, inplace=True)
df.iloc[:32]

I | Bus-1 | phase: A  I | Bus-1 | phase: B  I | Bus-1 | phase: C  \
time                                                                         
0.000000              1.814419             -0.011169           -258.969055   
0.000625             94.379097             -0.011169             -0.011496   
0.001250           -295.387756           -205.765198            199.992859   
0.001875             17.249544             -0.029567             -0.020706   
0.002500             31.293203             -0.011169             -0.011496   
0.003125           -293.600037             -0.011169             -0.011496   
0.003750           -205.946976             -0.020368             -0.011496   
0.004375            198.821899             -0.020368             94.418633   
0.005000            231.959045             -0.011169             -0.011496   
0.005625           -259.135956             -0.011169            -72.319206   
0.006250             -0.000936             -0.001970            295.224274   
0.006875             -0.000936           -150.920761             -0.002286   
0.007500             -0.000936             -0.001970             -0.002286   
0.008125              0.008279              0.007229              0.006924   
0.008750             -0.000936           -198.461197            191.906479   
0.009375              2.358104             -0.001970              0.006924   
0.010000             -0.000936              0.007229            -48.281105   
0.010625             -0.000936            295.138733             -6.172986   
0.011250           -191.838806             -0.001970             58.472004   
0.011875              0.008279             -0.001970             -0.204906   
0.012500             -0.000936            200.802994              0.006924   
0.013125             -0.000936           -100.666626            275.892487   
0.013750             -0.000936             -0.001970            295.021637   
0.014375              0.008279             -7.655538           -191.772903   
0.015000             -0.000936              0.007229             -0.002286   
0.015625              0.008279             -0.001970            297.858337   
0.016250             -0.000936            -48.701477           -242.630524   
0.016875            215.805145             -0.001970             -0.002286   
0.017500             -0.000936            203.369522            -41.170986   
0.018125             -0.000936             -0.001970              0.006924   
0.018750             -0.000936           -163.836166             -0.002286   
0.019375             -0.000936            289.462952           -153.919800   

          U | BusBar-1 | phase: A  U | BusBar-1 | phase: B  \
time                                                         
0.000000                -0.004381                 0.000359   
0.000625              -467.079742              -502.512817   
0.001250                64.714722              -254.557846   
0.001875                -0.004381                 0.000359   
0.002500              -464.078583                22.948507   
0.003125              -477.513794              -475.121094   
0.003750                -0.004381                 0.000359   
0.004375                -0.004381                 0.000359   
0.005000                -0.004381                -0.015178   
0.005625                -0.004381                -0.015178   
0.006250               466.806610              -371.722351   
0.006875                 0.011169               -41.359135   
0.007500                 0.011169               339.841156   
0.008125                 0.026719              -263.336243   
0.008750               505.588318              -446.797150   
0.009375                -7.064081                 0.015896   
0.010000               -79.822533                 0.015896   
0.010625                 0.011169               -82.858459   
0.011250                 0.011169                 0.015896   
0.011875               312.519531                 0.015

In [148]:
df.isna().any()

I | Bus-1 | phase: A           True
I | Bus-1 | phase: B           True
I | Bus-1 | phase: C           True
U | BusBar-1 | phase: A        True
U | BusBar-1 | phase: B       False
U | BusBar-1 | phase: C        True
U | BusBar-1 | phase: N        True
U | CableLine-1 | phase: A    False
U | CableLine-1 | phase: B    False
U | CableLine-1 | phase: C     True
I | Bus-2 | phase: A          False
I | Bus-2 | phase: B           True
I | Bus-2 | phase: C           True
U | BusBar-2 | phase: A        True
U | BusBar-2 | phase: B        True
U | BusBar-2 | phase: C        True
U | BusBar-2 | phase: N        True
U | CableLine-2 | phase: A     True
U | CableLine-2 | phase: B    False
U | CableLine-2 | phase: C    False
dtype: bool

In [132]:
np.fft.fft(df.iloc[:window_size],axis=0)

array([[-4.52209997e+02   +0.j        ,  1.12633877e+02   +0.j        ,
         6.93283317e+02   +0.j        ,  1.65327313e+02   +0.j        ,
        -1.99658621e+03   +0.j        , -2.02062274e+03   +0.j        ,
        -5.65851576e+02   +0.j        , -2.10167555e+02   +0.j        ,
        -2.34265911e+03   +0.j        , -5.01919181e+02   +0.j        ,
        -4.31536394e+02   +0.j        ,  9.81884777e+02   +0.j        ,
        -1.12751395e+03   +0.j        , -1.50586541e+03   +0.j        ,
        -1.65801259e+02   +0.j        , -6.75240609e+02   +0.j        ,
         6.15864043e+02   +0.j        ,  9.84645492e+02   +0.j        ,
         1.63727238e+03   +0.j        ,  2.09054548e+03   +0.j        ],
       [ 1.69181146e-01 +430.07711648j, -3.93125395e+01 +481.21384924j,
        -7.75102007e+02 -100.58036902j, -1.62972596e+03 +394.78843462j,
         3.55494695e+02 +758.87939479j, -2.85261483e+01 -917.47914979j,
        -6.92892522e+02 -221.64050859j,  9.25403556e+02  +39.76

In [123]:
osc_fft = np.abs(np.fft.fft(np.fft.fft(df.iloc[:window_size],axis=0)))

In [124]:
osc_fft 

array([[ 4714.51730848,  9937.66243962,  6449.45831527,  3396.49029021,
         3649.0592307 ,  8353.57031073,  1688.6835088 ,  1109.74853219,
         4738.86798066,  2397.29499427,  3556.96018727,  2397.29499427,
         4738.86798066,  1109.74853219,  1688.6835088 ,  8353.57031073,
         3649.0592307 ,  3396.49029021,  6449.45831527,  9937.66243962],
       [ 9092.71999173,  5432.97405691,  3132.28390263,  3845.03951143,
         4910.85304076,  3884.54054807,  5377.98751218,  2808.16005954,
         2258.61279576,  1347.87601564,  3385.94259288,  1683.5570973 ,
         6461.93797951,  8137.82667053,  7901.47079782,  2283.93154025,
         9971.13675903,  3816.77566886,  4543.66743465,  2627.86434906],
       [ 3640.98195652,  1614.26305442,  3049.59203359,  1687.52567483,
         3216.97501599,  3325.33572109,  4283.45607317,  2003.02738028,
         3570.78847594,  1848.97584395,  2838.44218897,  2345.06676001,
         1430.10274883,  6961.5754784 ,  4021.98291615,  6649.

In [85]:
osc_fft[1]/16

array([81.62105464])

In [108]:
window_size = 32
step_size = 1
unread = []
rec = comtrade.load("../../datasets/pqd/raw/f_network = 50 and f_rate = 1600/f758347852450afce8b2b2662351b0ac.cfg")
osc_df = rec.to_dataframe()
#osc_df = comtrade.load_as_dataframe('../../datasets/pqd/test/913f9526b55d822a6e47650b3afa244a.cfg')
osc_columns = osc_df.columns
osc_features = []
to_drop = []
for column in osc_columns:
    if column in features:
        osc_features.append(column)
    else:
        to_drop.append(column)
osc_df.drop(columns=to_drop, inplace=True)
osc_fft = np.abs(np.fft.fft(osc_df.iloc[:window_size],axis=0))
for i in range(window_size, osc_df.shape[0], step_size):
    window_fft = np.abs(np.fft.fft(osc_df.iloc[i - window_size: i],axis=0))
    osc_fft = np.maximum(osc_fft, window_fft)
h1 = osc_fft[1]
hx = np.max(osc_fft[2:16], axis=0)
h1_df = pd.DataFrame([dict(zip(osc_features, h1))])
hx_df = pd.DataFrame([dict(zip(osc_features, hx))])

In [109]:
h1

array([          nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan, 1363.60167485,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan])

In [110]:
hx_df

I | Bus-1 | phase: A  I | Bus-1 | phase: B  I | Bus-1 | phase: C  \
0                   NaN                   NaN                   NaN   

   U | BusBar-1 | phase: A  U | BusBar-1 | phase: B  U | BusBar-1 | phase: C  \
0                      NaN                      NaN                      NaN   

   U | BusBar-1 | phase: N  U | CableLine-1 | phase: A  \
0                      NaN                         NaN   

   U | CableLine-1 | phase: B  U | CableLine-1 | phase: C  \
0                         NaN                         NaN   

   I | Bus-2 | phase: A  I | Bus-2 | phase: B  I | Bus-2 | phase: C  \
0                   NaN           3091.837801                   NaN   

   U | BusBar-2 | phase: A  U | BusBar-2 | phase: B  U | BusBar-2 | phase: C  \
0                      NaN                      NaN                      NaN   

   U | BusBar-2 | phase: N  U | CableLine-2 | phase: A  \
0                      NaN                         NaN   

   U | CableLine-2 | phase: B  U | CableLine-2 | phase: C  
0                         NaN                         NaN

In [111]:
osc_fft[1]

array([          nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan, 1363.60167485,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan])

In [22]:
osc_df

I | Bus-1 | phase: A  I | Bus-1 | phase: B  I | Bus-1 | phase: C  \
time                                                                         
0.000000              0.006539              0.012861              0.004874   
0.000625              0.006539              0.003666              0.014090   
0.001250              0.006539              0.012861              0.004874   
0.001875              0.015740              0.012861              0.014090   
0.002500              0.006539              0.003666              0.014090   
...                        ...                   ...                   ...   
6.496875              0.015740              0.003666              0.014090   
6.497500              0.006539              0.003666              0.004874   
6.498125              0.006539              0.003666              0.004874   
6.498750             -0.002662              0.012861              0.004874   
6.499375              0.006539             -0.005529             -0.004342   

          I | Bus-1 | phase: N  U | BusBar-1 | phase: A  \
time                                                      
0.000000              0.001233                -0.138015   
0.000625              0.003615                 0.216402   
0.001250              0.005997                -0.121138   
0.001875              0.003615                -0.138015   
0.002500              0.003615                 0.233279   
...                        ...                      ...   
6.496875              0.001233                 0.182648   
6.497500              0.001233                -0.087384   
6.498125              0.003615                -0.188646   
6.498750              0.003615                 0.216402   
6.499375              0.001233                -0.121138   

          U | BusBar-1 | phase: B  U | BusBar-1 | phase: C  \
time                                                         
0.000000                 0.112346                -0.109021   
0.000625                -0.107146                 0.161043   
0.001250                 0.146114                -0.109021   
0.001875                 0.027926                -0.092142   
0.002500                -0.056494                 0.161043   
...                           ...                      ...   
6.496875                -0.056494                 0.127285   
6.497500                 0.044810                -0.024626   
6.498125                 0.095462                -0.159658   
6.498750                -0.090262                 0.161043   
6.499375                 0.095462                -0.075263   

          U | BusBar-1 | phase: N  
time                               
0.000000                -0.157024  
0.000625                 0.214314  
0.001250                -0.173903  
0.001875                -0.140145  
0.002500                 0.214314  
...                           ...  
6.496875                 0.197435  
6.497500                -0.089508  
6.498125                -0.173903  
6.498750                 0.214314  
6.499375                -0.123266  

[10400 rows x 8 columns]

In [90]:
rec._cfg.analog_channels[3].primary

TypeError: list indices must be integers or slices, not str