In [10]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_model, train_fft_model, evaluate_model
from models.conv_mlp import CONV_MLP, CONV_FFT_MLP
import random
import os

In [11]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [12]:
seed = 206
seed_everything(seed)

In [13]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005

In [14]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [15]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [16]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [17]:
model = CONV_FFT_MLP(frame_size=32)

In [18]:
train_fft_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.1129015017551932
32.439378489765055


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98186937 0.92654834 0.28279387]
epoch 0  0.7304038598876635


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.055177255852825305
7.375630470027179


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98550105 0.95460489 0.55534709]
epoch 1  0.8318176780811801


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.04513097925358683
4.748480141530047


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98560383 0.90802775 0.38358608]
epoch 2  0.7590725538963841


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.03859127529851967
3.9372237233533016


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98722127 0.94738816 0.48979592]
epoch 3  0.8081351174485657


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.03469893815707453
3.422486303951706


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99107412 0.96791153 0.49370277]
epoch 4  0.8175628081525174


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.030353926308578954
3.131700004762693


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98774216 0.95964797 0.61285008]
epoch 5  0.8534134040344079


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.027798823684063743
2.879470293710364


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9881014  0.95269506 0.49014778]
epoch 6  0.8103147474125082


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.02508881465189484
2.975610947890448


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99045736 0.96753247 0.67013889]
epoch 7  0.8760429051436617


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.023031663644365513
2.8946467388337154


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99077134 0.96823333 0.59964093]
epoch 8  0.8528818682211917


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.020151285903972593
2.7711597204636744


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98781848 0.95752969 0.61971831]
epoch 9  0.8550221597460603


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01984904746522125
2.662950251656881


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97883069 0.9509688  0.70096463]
epoch 10  0.8769213725106481


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.019246247921790915
2.7146360302607873


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98933517 0.97456295 0.65945946]
epoch 11  0.8744525242503448


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.016706773434609808
2.3901609454678803


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99072436 0.98031279 0.68301226]
epoch 12  0.8846831364174879


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0176402067603915
2.658065361163944


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99019776 0.97014788 0.58773784]
epoch 13  0.8493611635833999


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.015068708491357415
2.3938697643838136


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98985906 0.97146575 0.69949066]
epoch 14  0.8869384899465889


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.015268553626496451
2.455666872846762


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99002751 0.9689544  0.63073852]
epoch 15  0.863240144054993


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01275525635544695
2.215841552039926


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98831515 0.97342501 0.73448276]
epoch 16  0.8987409733026827


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.013055155386743603
2.271835999383574


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98910619 0.97039993 0.65275142]
epoch 17  0.8707525140299383


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.012384886243536574
2.573588135397899


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99013229 0.97093669 0.63054187]
epoch 18  0.8638702832359259


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.011214242902946718
2.2691975997519935


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98870323 0.96951049 0.65472313]
epoch 19  0.8709789503144894


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.011132282508455806
2.2466821918986906


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98730921 0.96486159 0.66666667]
epoch 20  0.8729458220492213


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.011866826890613268
2.3888574294302254


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98671283 0.96293571 0.52959502]
epoch 21  0.8264145202038078


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.011849162443004635
2.408245719647995


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99114126 0.97445863 0.60624071]
epoch 22  0.8572802039129978


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00941998117611504
2.0985570425737565


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98862514 0.96350365 0.63736264]
epoch 23  0.8631638106220373


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008884326728781526
2.0294976002810183


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99326541 0.98173516 0.71936759]
epoch 24  0.8981227201987085


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.009491886240158936
2.2359138431612715


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98765114 0.96462902 0.65523156]
epoch 25  0.869170576821801


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00849402372116087
2.3162892619931967


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99018595 0.97192787 0.66666667]
epoch 26  0.8762601615710931


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0093491085969455
2.349310614612313


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98681168 0.96043268 0.68500688]
epoch 27  0.8774170790946073


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007464811055771911
1.9676272974366769


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99178343 0.97905041 0.65486726]
epoch 28  0.8752336974029423


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006731893884367575
2.0404923468889398


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98931009 0.96749908 0.60229885]
epoch 29  0.8530360085435723


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008732021683929309
2.1470481866255433


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98933792 0.97257736 0.68551237]
epoch 30  0.8824758814856933


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006326041311057317
2.08206902826836


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98849485 0.96967456 0.57956449]
epoch 31  0.8459112986722825


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007987250813166907
2.1925778238129565


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98809832 0.97185706 0.57006369]
epoch 32  0.8433396920049651


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00664399256438708
1.9823859455771515


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98978278 0.97357156 0.75517241]
epoch 33  0.9061755839950179


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007038110362023123
2.1350308906677076


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99018848 0.97614442 0.73904762]
epoch 34  0.9017935087931956


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007635300179808265
1.9414539866807279


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99161038 0.97741047 0.69815195]
epoch 35  0.8890575987853824


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005764630663164325
1.7971766513047522


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98932231 0.97248892 0.65480427]
epoch 36  0.8722051677930125


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008171443918699844
2.3219607053228963


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98836361 0.96162528 0.64091559]
epoch 37  0.8636348270026026


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006742858540584101
1.963731336091823


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98885302 0.96908955 0.65726375]
epoch 38  0.871735440621908


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007002010969801736
2.082755737480931


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99177681 0.97569922 0.68032787]
epoch 39  0.8826013002876353


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0066398613871574376
1.8535463613528735


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98935618 0.97382488 0.57446809]
epoch 40  0.8458830495025081


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004603572760926515
1.7481614603093028


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98625915 0.96514445 0.69943289]
epoch 41  0.8836121656381049


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0069919410408494555
2.0625015051702698


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99044504 0.97510412 0.69879518]
epoch 42  0.8881147788772298


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006511475772966442
1.9726112566934229


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98736896 0.95674348 0.55820106]
epoch 43  0.8341045017096825


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006887477044283796
2.2496051174536866


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99272148 0.97765977 0.65970772]
epoch 44  0.8766963239329154


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0049131116063926995
1.7951755447186972


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99301724 0.98139492 0.68762279]
epoch 45  0.8873449845728066


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005920540785062102
1.8457411473781422


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9899094  0.9682378  0.65413534]
epoch 46  0.8707608458097864


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0052726842919436235
1.915843411759919


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98990593 0.97333702 0.672     ]
epoch 47  0.8784143185288177


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00772931924075532
1.9057518852687225


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99253892 0.98275229 0.71669794]
epoch 48  0.8973297174867666


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0053152257679378095
1.8797434959139911


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99122997 0.97298803 0.61714286]
epoch 49  0.8604536159229087


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006363519923716427
2.108686980923343


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99372158 0.98660836 0.74452555]
epoch 50  0.9082851650481852


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006508192152213466
1.8837652481189744


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98849282 0.96907409 0.57677903]
epoch 51  0.844781978806755


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005603747377456938
1.8557418896309894


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98686695 0.96842302 0.71103896]
epoch 52  0.8887763110868829


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003342870413263178
1.68211517181607


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98973764 0.97412678 0.71905697]
epoch 53  0.894307132541717


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006601605970818408
1.972154875830948


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99138302 0.97662433 0.69485294]
epoch 54  0.8876200995053343


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0053907552732072195
1.9268561650289402


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98662336 0.96502712 0.75142315]
epoch 55  0.9010245426292903


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004004201648084178
1.8406968502293377


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98989725 0.9792976  0.77922078]
epoch 56  0.9161385430586311


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00510151096589555
1.9162646624158295


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99018848 0.97106344 0.59484778]
epoch 57  0.8520332336352198


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0054498325067819115
1.821184995146258


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99016534 0.97006548 0.70697674]
epoch 58  0.889069189479956


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004959679647744473
1.7128466597511538


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99043845 0.97648686 0.67145422]
epoch 59  0.8794598440864211


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00380893866079978
1.7321424566255212


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98905344 0.96849885 0.688     ]
epoch 60  0.8818507634036186


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0052455435371231846
1.6888551364444364


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99118014 0.97912047 0.77757685]
epoch 61  0.9159591556021381


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004828721337025585
1.7631496907014867


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98669528 0.94645941 0.56570156]
epoch 62  0.8329520835902193


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00408344087181676
1.630844775564372


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99017495 0.96694215 0.60835509]
epoch 63  0.8551573982990747


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007213881054187934
1.827438490499706


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99085497 0.97602645 0.64972777]
epoch 64  0.8722030649833523


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004034652495368424
1.6782260143352974


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99171043 0.97852116 0.57680251]
epoch 65  0.8490113653384189


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003400616182792928
1.5510503903673905


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98949371 0.97351897 0.66135458]
epoch 66  0.8747890881295092


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007044528960633297
2.0142566675217


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99139044 0.96806723 0.63529412]
epoch 67  0.8649172626433268


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0033729845455953843
1.5972306500714908


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99059615 0.97892315 0.69808028]
epoch 68  0.8891998597137322


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003822019206515463
1.5519173056254396


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98915756 0.97474189 0.70566038]
epoch 69  0.8898532749514972


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005041692532225655
1.7224036218632908


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99098088 0.97991379 0.70955882]
epoch 70  0.8934844972167464


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004821780804102572
1.7880994899378175


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99091809 0.97535953 0.6212766 ]
epoch 71  0.8625180724660974


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00550845358862905
2.025757612664352


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9886447  0.9686747  0.65470852]
epoch 72  0.8706759744782122


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0036067006063697804
1.64894812812673


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99027706 0.97361187 0.64502165]
epoch 73  0.8696368601416363


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0028617326635094085
1.5549799133803566


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98949996 0.97421203 0.70337478]
epoch 74  0.889028923108708


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005152574496174355
1.7929391640351293


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99120462 0.9701892  0.60236887]
epoch 75  0.8545875632915035


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003500999120745961
1.5531160605639158


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99138715 0.97423673 0.60855263]
epoch 76  0.8580588353082517


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004174312494730746
1.7971776087120084


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99082648 0.97786795 0.71454219]
epoch 77  0.8944122046759927


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004470850023373032
1.8067924424669337


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98271006 0.94345211 0.36585366]
epoch 78  0.7640052738921455


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00282268399153251
1.6122524354002559


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9888674  0.97284271 0.7385159 ]
epoch 79  0.9000753362019566


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004780857471180282
1.6849948766907137


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9845715  0.96494921 0.67148014]
epoch 80  0.8736669518150291


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0037355013129219327
1.633405031150616


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99164945 0.97734868 0.67207792]
epoch 81  0.8803586842937602


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00303044699590094
1.5337781417785974


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99082727 0.97743391 0.70848708]
epoch 82  0.8922494222986005


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003996519885385798
1.6030315460916418


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99143017 0.97774481 0.75121951]
epoch 83  0.9067981634275734


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0030399263394767623
1.6259489500975461


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99047537 0.97229311 0.55280899]
epoch 84  0.8385258226873978


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005928397860751788
1.8050497615178263


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99115579 0.97776961 0.7027027 ]
epoch 85  0.8905427008717223


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0030136709785965085
1.555892526460869


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98846137 0.9711188  0.75986842]
epoch 86  0.9064828635614702


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004465995705684367
1.7858773005449307


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99052704 0.96198254 0.5679677 ]
epoch 87  0.8401590932137112


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0027005574806750953
1.5874844773900092


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99000345 0.97164496 0.60854701]
epoch 88  0.8567318057680398


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007633757347173985
1.7928723708804872


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99123148 0.96107332 0.53785311]
epoch 89  0.8300526352808125


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0036195129575269094
1.523937234521157


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9895162  0.9685511  0.67673716]
epoch 90  0.8782681543030032


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0035405895818963512
1.6166482842250036


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98841266 0.97391304 0.67226891]
epoch 91  0.8781982050890008


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0024238648989923684
1.4230742703289467


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99058672 0.97379669 0.73187184]
epoch 92  0.8987517494740876


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003475155151993193
1.467742514775519


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99143238 0.97745334 0.7145359 ]
epoch 93  0.8944738741495227


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00335159527535249
1.4406226360577576


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99032633 0.97462963 0.71301248]
epoch 94  0.8926561442138081


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004397893488989914
1.6680312304770921


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98929003 0.97117314 0.60159363]
epoch 95  0.8540189339686038


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0017331738324870075
1.3762355206010277


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98904216 0.96954979 0.69984448]
epoch 96  0.8861454732147793


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003722312517109842
1.507741537427021


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99074513 0.96637002 0.63585434]
epoch 97  0.8643231634014418


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0033565321693468445
1.7139895602724147


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99103371 0.97581975 0.66269841]
epoch 98  0.8765172899024766


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00361565511672475
1.5081885584326007


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99168569 0.98119816 0.77558348]
epoch 99  0.9161557776626169


### evaluate_model(model, test_dataset)

In [ ]:
random.randint(0, 256)

In [ ]:
random.randint(0, 256)

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [2]:
random.randint(0, 256)

2