In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_model, train_fft_model, evaluate_model
from models.conv_mlp import CONV_MLP
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 29
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = CONV_MLP(frame_size=32)

In [9]:
train_fft_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.12632489455978577
31.66951276077382


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97940386 0.86521783 0.30116959]
epoch 0  0.715263762977592


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.05357310637657543
4.29103939556488


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.990323   0.83001884 0.17520661]
epoch 1  0.6651828162356407


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0402951889283877
4.247592595752015


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98863003 0.93342313 0.43090316]
epoch 2  0.7843187698821042


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.034291588728622494
3.978505344361495


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9915163  0.97488458 0.62214411]
epoch 3  0.8628483307499044


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.030844550369922733
3.696542775606473


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99109639 0.96819983 0.5210728 ]
epoch 4  0.8267896740878636


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.02795991965485434
3.9045265747169204


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98833225 0.95159342 0.46882793]
epoch 5  0.8029178670176026


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.023124254459770215
3.423271327813058


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9895623  0.97277274 0.70240296]
epoch 6  0.8882459990675575


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.022575867022681113
3.3309498150245855


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99241379 0.9767826  0.61950287]
epoch 7  0.8628997539626918


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.020080056375555003
3.355502530351067


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98972971 0.97314875 0.68259386]
epoch 8  0.8818241045017868


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01863911877029511
3.1057855743891896


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9910476  0.95253496 0.52004582]
epoch 9  0.8212094594621431


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.016957092090730094
2.8794338133117257


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98817255 0.97286207 0.69659443]
epoch 10  0.8858763503813601


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.017231047874392186
2.905128942347405


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98784406 0.97461187 0.66352201]
epoch 11  0.8753259804455668


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.015695032111404994
2.7155225949794115


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99301724 0.97355479 0.65940902]
epoch 12  0.8753270180703132


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01508319010604777
2.6020176373039674


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98960319 0.96947634 0.57837181]
epoch 13  0.845817111988535


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.014698948482095842
2.611831157695831


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99075115 0.97334194 0.58970359]
epoch 14  0.8512655586902816


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01330934307371569
2.6324333799142368


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99147961 0.9833655  0.7184466 ]
epoch 15  0.8977639029065672


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01084813504245046
2.444458397353944


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99199173 0.97751041 0.67911715]
epoch 16  0.8828730976521895


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01169766680484672
2.603649445505358


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99121069 0.97437331 0.64801178]
epoch 17  0.8711985926833904


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.009594128492021674
2.4933088967687542


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99066145 0.97522502 0.7029703 ]
epoch 18  0.889618919459027


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.009376928055411583
2.5479775180990445


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98762958 0.97150562 0.68156425]
epoch 19  0.8802331494153868


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.010388463968259145
2.4661567261637605


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99021003 0.97886149 0.68933539]
epoch 20  0.886135637574274


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008129523104552085
2.2943647137902357


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99124358 0.97725171 0.65168539]
epoch 21  0.8733935625547327


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008392107946925114
2.4127556295793893


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98675922 0.9589301  0.64054054]
epoch 22  0.862076619963095


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.009050498730012345
2.610113251870173


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.988978   0.97164179 0.7238422 ]
epoch 23  0.8948206618233395


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006675148065117714
2.304421917521978


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98594326 0.97023587 0.76079734]
epoch 24  0.9056588225577707


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008756396388024066
2.4637590690804703


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98741438 0.9631638  0.59929078]
epoch 25  0.8499563210849073


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008238371996565344
2.40609373797871


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99122128 0.97789698 0.71001757]
epoch 26  0.8930452753506205


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006269166726563637
2.14825734649106


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98984422 0.97358491 0.60348162]
epoch 27  0.8556369170305445


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007246832289350927
2.620011594995581


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98916409 0.96752457 0.60677467]
epoch 28  0.854487774155952


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005604302148197131
2.35739431461392


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99122052 0.97897175 0.72325976]
epoch 29  0.8978173427902417


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007733933221405425
2.605554891532207


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98942754 0.97020882 0.65511265]
epoch 30  0.8715830027736132


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00517833219945143
2.020503701982557


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98928143 0.96790493 0.68965517]
epoch 31  0.8822805101650343


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006104634614548668
2.226025188666839


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99163577 0.97871553 0.68387097]
epoch 32  0.8847407546743596


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008664586714849884
2.3863376329444517


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99040489 0.97373775 0.70442478]
epoch 33  0.8895224713463968


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005091030555557932
2.066650902680303


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99018595 0.97426846 0.67736758]
epoch 34  0.8806073297558384


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008375158852776197
2.651896334740905


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99408335 0.98525236 0.79927007]
epoch 35  0.9262019276757706


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005870654695673764
2.0647981186422233


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9893996  0.97361797 0.75675676]
epoch 36  0.9065914422262998


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005826986889717784
2.103972799846524


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98965443 0.97579523 0.75645756]
epoch 37  0.9073024100315848


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007626287245386368
2.4114668204982666


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9895243  0.97365236 0.72231687]
epoch 38  0.8951645085739094


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004661407373589861
2.1513864997720815


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99124736 0.97159885 0.61918605]
epoch 39  0.860677416986236


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005369269378847439
2.0149075683565845


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98882898 0.97321182 0.6958042 ]
epoch 40  0.8859483333335006


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008516033502697123
2.4457432703866604


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99209196 0.98296658 0.71521036]
epoch 41  0.8967562972156277


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0046044880255166265
1.8776457346134363


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98858565 0.9721034  0.72241993]
epoch 42  0.8943696609141693


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004962930969712279
2.097077608751076


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98994932 0.97306335 0.72727273]
epoch 43  0.896761797305803


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005606284184558011
2.041436463043675


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99088407 0.97528922 0.68336315]
epoch 44  0.8831788131204982


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00476634869691016
2.0468394509086374


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99155682 0.97773298 0.62880325]
epoch 45  0.866031014537603


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005609827795821969
2.1203548309127407


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99040736 0.97728326 0.69387755]
epoch 46  0.8871893930679389


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005755018333621871
2.0898411033763042


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99122203 0.97312878 0.6432    ]
epoch 47  0.8691836027646481


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005132747336388508
2.123417301803399


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98956858 0.97446848 0.72563177]
epoch 48  0.8965562753597226


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004160099048853703
2.115816603267462


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98825547 0.97172189 0.77217391]
epoch 49  0.9107170877725231


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0050610843216675975
2.1080844275026105


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99150166 0.98057897 0.69216061]
epoch 50  0.8880804131173562


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0032142334108948276
1.708070901201491


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99387614 0.98366373 0.71641791]
epoch 51  0.897985927696455


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005028260242692399
2.0785845202342195


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98851069 0.97083952 0.63947798]
epoch 52  0.8662760649699316


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00476574647199367
1.827422205855959


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98414358 0.97110037 0.62158273]
epoch 53  0.8589422288714464


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004222301388248615
2.0822647894126436


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99008881 0.97540147 0.76666667]
epoch 54  0.9107189826051488


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003994832635860202
1.8595567825087775


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99250646 0.97593118 0.57082452]
epoch 55  0.8464207213026543


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004589127725465865
1.9997200585549861


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99032549 0.96712303 0.60063898]
epoch 56  0.8526958345133476


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004305546257562366
2.0465491244557947


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99030966 0.97729371 0.65961199]
epoch 57  0.8757384527133931


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003163761645820293
1.7996161383035492


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98829482 0.97095901 0.70748299]
epoch 58  0.8889122719720789


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004539097981852552
1.934971125341294


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98740468 0.96924231 0.6970684 ]
epoch 59  0.8845717975829329


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004518996831716054
1.900846159005312


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98629313 0.97084143 0.71323529]
epoch 60  0.8901232854767778


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003957278693690021
1.8139355577360188


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9870697  0.9718231  0.73260073]
epoch 61  0.8971645125473322


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0042940383359068085
1.8806260241314126


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99033214 0.97990927 0.76556777]
epoch 62  0.9119363925911163


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006173778072041851
1.9809855501754572


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98871099 0.9759137  0.76140351]
epoch 63  0.9086760667021229


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003170882100687335
1.7230654439030242


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98856874 0.97378208 0.78106509]
epoch 64  0.9144719671005767


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0041899103846667176
1.7696491341571299


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99212395 0.98164715 0.74169742]
epoch 65  0.9051561711780541


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00437264410763011
1.8410759812079416


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99216193 0.98131706 0.74829932]
epoch 66  0.9072594347410198


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0032958185396392164
1.8601250054287959


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9924262  0.9740441  0.64454976]
epoch 67  0.870340019542172


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003861538933589079
1.9038958826410208


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99111016 0.97344638 0.69435216]
epoch 68  0.8863028988480277


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0047611810792789235
1.9236754367177735


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99313679 0.984822   0.72852234]
epoch 69  0.9021603765546705


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0027437995052427867
1.5588359680692274


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98910993 0.9743685  0.73863636]
epoch 70  0.9007049308598606


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0038129563888946298
1.8807700731365098


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98901759 0.97100774 0.68610635]
epoch 71  0.8820438909953818


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004034258335243276
1.811975884853692


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99095763 0.97530638 0.61471861]
epoch 72  0.8603275428378647


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005353092354636503
1.9618639395222282


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98930091 0.97058824 0.59957173]
epoch 73  0.8531536254664976


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0027809180682710276
1.6640533447816386


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99066064 0.97749908 0.69500924]
epoch 74  0.8877229870830586


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0040916765685708
1.786065387927776


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98877752 0.97224292 0.76208178]
epoch 75  0.9077007420581555


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00596178262594605
1.9886257027637297


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98738007 0.97602361 0.70532915]
epoch 76  0.8895776095171573


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0026758839644542855
1.6164316571101516


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99136264 0.98031605 0.76515152]
epoch 77  0.9122767358227811


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003873033827917778
1.8392883000983349


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98930734 0.97560071 0.66787004]
epoch 78  0.8775926933447854


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0032771031877589975
1.6914349310635541


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98715139 0.97287758 0.7238422 ]
epoch 79  0.8946237210805092


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00310454347265545
1.8448075121861465


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9884683  0.97402476 0.77536232]
epoch 80  0.9126184607660739


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005387259780359416
1.9151917081899956


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98884822 0.96394185 0.58177278]
epoch 81  0.8448542872653975


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003634516587327272
1.7053867529549882


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9853621  0.96268375 0.6552795 ]
epoch 82  0.8677751176258867


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0036445216218767167
1.8711092908401998


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9896066 0.9752834 0.7456446]
epoch 83  0.9035115335598166


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0025183117171395934
1.7249467567190742


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99076472 0.98169105 0.71157168]
epoch 84  0.8946758130911112


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0035108093454367783
1.7702014971011963


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98762154 0.97182967 0.79251701]
epoch 85  0.9173227368395905


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0044223995178346125
1.9606909912224912


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99165663 0.98162002 0.83179298]
epoch 86  0.9350232105573536


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003994686063739134
1.755896194606591


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99086837 0.98104134 0.7715736 ]
epoch 87  0.9144944366111448


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0019517437165137163
1.481566422406653


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9908454  0.97781491 0.7862069 ]
epoch 88  0.9182890691840587


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005303714767591092
1.9138054712474712


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98853438 0.97707231 0.78214286]
epoch 89  0.9159165143170286


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0022468081125386306
1.5097035095554603


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98783205 0.97252336 0.78965517]
epoch 90  0.9166701949620214


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.002045199481704842
1.4918163931284107


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99105299 0.98031969 0.7723133 ]
epoch 91  0.914561993419804


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004314642766774341
1.8339808611715598


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98884438 0.97422157 0.62758621]
epoch 92  0.8635507177847163


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005454843708529294
2.0510086771215503


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98489478 0.95552205 0.57068742]
epoch 93  0.8370347497740749


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003569528757220763
1.4936205814812462


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99030214 0.97890842 0.72249589]
epoch 94  0.8972354850633644


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.002942609584498018
1.5557034537655128


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99177185 0.97883353 0.70068027]
epoch 95  0.8904285525622124


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003322787415821099
1.5653500668628015


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98953059 0.97677012 0.7826087 ]
epoch 96  0.916303135237044


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0015652177067372183
1.3738612205677454


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99029043 0.97556913 0.71003717]
epoch 97  0.8919655769639473


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0027945999195371374
1.526393395184981


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99000947 0.97455824 0.62478778]
epoch 98  0.8631184960570533


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004640911746188632
1.8230182117566436


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98599632 0.96969697 0.74264706]
epoch 99  0.8994467818649049


### evaluate_model(model, test_dataset)

In [ ]:
random.randint(0, 256)

In [ ]:
random.randint(0, 256)

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [6]:
random.randint(0, 256)

171