In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam
from tqdm.auto import tqdm, trange
from pqd_trainer import train_model, train_ae_model, evaluate_model
from models.conv_mlp import CONV_MLP
from models.conv_ae_mlp import CONV_AE_MLP, MLP
from sklearn.metrics import f1_score, balanced_accuracy_score
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 42
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005
device='cpu'

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = CONV_AE_MLP(frame_size=32)

In [9]:
train_ae_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98268214 0.94343116 0.26666667]
epoch 0  0.7309266555340126


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98822012 0.87617712 0.23657475]
epoch 1  0.7003239950669684


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98362928 0.83740522 0.2300885 ]
epoch 2  0.6837076651900985


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98851567 0.95905352 0.55399061]
epoch 3  0.8338532665037611


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98910469 0.96341919 0.57979502]
epoch 4  0.8441062993153251


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98689805 0.95574086 0.53576865]
epoch 5  0.8261358508684552


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99166415 0.96530027 0.55757576]
epoch 6  0.8381800577050322


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98283518 0.95160229 0.65831843]
epoch 7  0.864251967460539


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98942624 0.96998978 0.56081946]
epoch 8  0.8400784952484998


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98915439 0.96815994 0.62407132]
epoch 9  0.8604618837118024


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9896516  0.96322503 0.59970888]
epoch 10  0.8508618362630239


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99137038 0.97489003 0.64285714]
epoch 11  0.8697058517792146


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98734506 0.96842105 0.63768116]
epoch 12  0.8644824252533129


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98681489 0.95997777 0.61165049]
epoch 13  0.8528143807596275


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9853977  0.96439224 0.61842105]
epoch 14  0.8560703317384007


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9888975  0.92778741 0.40763052]
epoch 15  0.77477180789784


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98767764 0.96645042 0.70500928]
epoch 16  0.8863791124052395


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98856996 0.96784892 0.60040568]
epoch 17  0.8522748507912682


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9891843  0.97001015 0.69097222]
epoch 18  0.883388890158007


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98906419 0.96924767 0.68694097]
epoch 19  0.8817509401957654


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9887989  0.96132182 0.53174603]
epoch 20  0.8272889154557571


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9909475  0.97455283 0.69444444]
epoch 21  0.8866482568182651


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9890431  0.96804581 0.65895954]
epoch 22  0.8720161472966884


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98940477 0.97443443 0.70454545]
epoch 23  0.8894615524857463


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98886644 0.96725912 0.66866567]
epoch 24  0.8749304093699667


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98842861 0.97207015 0.69798658]
epoch 25  0.8861617803394356


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98801414 0.96964155 0.65714286]
epoch 26  0.8715995165241525


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98857192 0.96600301 0.65804598]
epoch 27  0.8708736339481692


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98928064 0.97524478 0.79292035]
epoch 28  0.9191485918811556


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98896475 0.96921936 0.70458716]
epoch 29  0.8875904205654964


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98603292 0.96216417 0.5959596 ]
epoch 30  0.8480522291537648


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99010071 0.97272477 0.63581489]
epoch 31  0.8662134573069334


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98433622 0.9664354  0.72789116]
epoch 32  0.8928875912294969


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98852846 0.973358   0.72523364]
epoch 33  0.8957067035757126


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99096386 0.97151396 0.66567608]
epoch 34  0.8760512985052388


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98896948 0.97012855 0.62992126]
epoch 35  0.8630064308267267


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98915943 0.97132181 0.70254111]
epoch 36  0.887674114547763


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98943117 0.96696921 0.68797565]
epoch 37  0.881458678518327


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99131407 0.97790923 0.71192661]
epoch 38  0.8937166362491538


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98819996 0.96987673 0.66920152]
epoch 39  0.875759401432867


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98997979 0.96691969 0.60632184]
epoch 40  0.8544071051703827


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98943027 0.97404157 0.71017274]
epoch 41  0.8912148602309474


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98787931 0.97190907 0.67293233]
epoch 42  0.8775735712660279


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99025106 0.97787242 0.69073783]
epoch 43  0.8862871032232916


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98586482 0.96565205 0.68926554]
epoch 44  0.8802608018216924


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98546873 0.96570263 0.69184891]
epoch 45  0.8810067563407697


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9833927  0.95578011 0.62641509]
epoch 46  0.85519596541392


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98781639 0.97192588 0.71474359]
epoch 47  0.891495287298207


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98793015 0.95694142 0.58635704]
epoch 48  0.8437428698468636


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98868184 0.9722274  0.67075038]
epoch 49  0.8772198754244934


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9888297  0.97195224 0.66543438]
epoch 50  0.8754054373635022


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98986341 0.97082476 0.64596273]
epoch 51  0.8688836360879507


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98904027 0.96925357 0.63063063]
epoch 52  0.862974822578355


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98860521 0.97312378 0.73422562]
epoch 53  0.8986515366242013


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98974315 0.97937286 0.6677686 ]
epoch 54  0.8789615345831349


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98579254 0.96506754 0.6615087 ]
epoch 55  0.8707895923204133


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98821708 0.97009658 0.66555184]
epoch 56  0.8746218342879212


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98823732 0.97476195 0.7037037 ]
epoch 57  0.8889009914055549


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9903363  0.96728227 0.62089552]
epoch 58  0.8595046972286688


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99005296 0.97771201 0.71575342]
epoch 59  0.8945061342360253


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98967475 0.97449216 0.66890756]
epoch 60  0.8776914933125765


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98812026 0.97204622 0.71803853]
epoch 61  0.8927350004751754


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98826452 0.9715089  0.72425249]
epoch 62  0.8946753048689796


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98686695 0.97308373 0.73413379]
epoch 63  0.8980281575627033


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98854028 0.96482318 0.59796807]
epoch 64  0.8504438418949049


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98571795 0.9622019  0.6752    ]
epoch 65  0.8743732849848458


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99083358 0.97397631 0.68277946]
epoch 66  0.8825297829144385


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98365451 0.96186323 0.70588235]
epoch 67  0.8838000293663463


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9891421  0.97391465 0.67659574]
epoch 68  0.8798841626992542


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98868022 0.97229453 0.69741697]
epoch 69  0.8861305745194853


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9857094  0.96918192 0.75925926]
epoch 70  0.9047168583924398


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98955243 0.97179204 0.60818713]
epoch 71  0.8565105337393546


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9886705  0.97436374 0.72826087]
epoch 72  0.8970983692147289


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99007178 0.97602803 0.66272189]
epoch 73  0.8762738992444953


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98617151 0.96216216 0.55007052]
epoch 74  0.8328013973707676


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9860835  0.9667426  0.67455621]
epoch 75  0.8757941029448832


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98486533 0.96211273 0.66536965]
epoch 76  0.8707825684994602


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98981653 0.97318861 0.6971831 ]
epoch 77  0.8867294105522143


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98748822 0.96624789 0.66233766]
epoch 78  0.8720245898244013


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98508103 0.96233522 0.68545994]
epoch 79  0.8776253942301566


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98799726 0.96836801 0.67826087]
epoch 80  0.8782087131725295


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9895225  0.96758569 0.60402685]
epoch 81  0.8537116798306416


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98929447 0.96946984 0.42280285]
epoch 82  0.7938557174935138


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98879684 0.97165617 0.68690702]
epoch 83  0.8824533435397605


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98926578 0.9738453  0.69343066]
epoch 84  0.8855139113190496


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99022773 0.97196435 0.64297254]
epoch 85  0.8683882069827916


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9895144  0.96662316 0.63141026]
epoch 86  0.8625159371028022


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98717344 0.96192726 0.64917127]
epoch 87  0.8660906545671702


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98834019 0.97064834 0.66539924]
epoch 88  0.8747959229819907


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98727016 0.96921789 0.70895522]
epoch 89  0.888481090716232


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99079332 0.96299783 0.58807947]
epoch 90  0.8472902092285421


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98773269 0.96862159 0.6722408 ]
epoch 91  0.8761983622705918


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98731139 0.96768132 0.70987654]
epoch 92  0.8882897504934611


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99034376 0.97546978 0.71705426]
epoch 93  0.8942892675166697


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9887544  0.97362556 0.72563177]
epoch 94  0.8960039085596261


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98742543 0.95914709 0.6       ]
epoch 95  0.8488575072443093


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98782534 0.97130732 0.68656716]
epoch 96  0.8818999397115723


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98881029 0.97138078 0.69793621]
epoch 97  0.8860424279204157


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98969869 0.97426368 0.71198569]
epoch 98  0.8919826854807368


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98959677 0.97486785 0.67826087]
epoch 99  0.8809084947876391
