In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_model, evaluate_model
from models.conv_mlp import CONV_MLP
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 2
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=256
lr = 0.0005

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = CONV_MLP(frame_size=32)

In [9]:
train_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.97457447 0.8590724  0.12298387]
epoch 0  0.6522102480018105


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98130001 0.91945289 0.29875519]
epoch 1  0.7331693623658352


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98027832 0.91884692 0.24011713]
epoch 2  0.713080791936657


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.97988065 0.91511706 0.32010243]
epoch 3  0.7383667146635745


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98457175 0.94442372 0.44338118]
epoch 4  0.7907922168446265


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98260015 0.93766012 0.42898551]
epoch 5  0.7830819240524544


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98307726 0.93673451 0.3902439 ]
epoch 6  0.7700185547946639


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98545876 0.94510427 0.43322476]
epoch 7  0.7879292621470215


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98538425 0.94576844 0.47226624]
epoch 8  0.8011396445409941


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98554196 0.94542703 0.44245142]
epoch 9  0.7911401378919215


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9869718  0.95732047 0.46850394]
epoch 10  0.8042654018109299


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98617711 0.95176492 0.4845679 ]
epoch 11  0.8075033101234937


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98896076 0.93040789 0.38191882]
epoch 12  0.7670958217473807


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98565908 0.9521576  0.50746269]
epoch 13  0.8150931220723115


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98646849 0.91281139 0.3755102 ]
epoch 14  0.7582633609655156


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98781695 0.94454485 0.42824601]
epoch 15  0.786869271949485


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9890928  0.94302292 0.38085743]
epoch 16  0.7709910498332136


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98655556 0.95599962 0.50294118]
epoch 17  0.8151654538430093


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98749569 0.95317632 0.46692607]
epoch 18  0.8025326914145509


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9879622  0.95568437 0.48460509]
epoch 19  0.8094172196372686


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98626374 0.94734841 0.49127182]
epoch 20  0.8082946565206274


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98874272 0.95830588 0.53333333]
epoch 21  0.8267939790911693


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98913843 0.95119246 0.44444444]
epoch 22  0.7949251107916305


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98797044 0.95947834 0.54187192]
epoch 23  0.829773568237096


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98970227 0.96498845 0.53583618]
epoch 24  0.8301756336003842


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9890555  0.9558037  0.49536424]
epoch 25  0.8134078112050651


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9883751  0.96290066 0.58874459]
epoch 26  0.846673449702725


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98974933 0.95572233 0.49326146]
epoch 27  0.8129110381313821


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98939106 0.96252319 0.51840491]
epoch 28  0.8234397211379019


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98354551 0.95800477 0.53225806]
epoch 29  0.824602780729974


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98884373 0.96946706 0.57142857]
epoch 30  0.8432464528470908


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98964803 0.96482133 0.52996845]
epoch 31  0.8281459389228055


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98876599 0.95639864 0.51590909]
epoch 32  0.8203579062568466


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98959188 0.96759859 0.57013575]
epoch 33  0.8424420734209308


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.99046304 0.96375187 0.53297443]
epoch 34  0.8290631117788206


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98703195 0.92872902 0.3660419 ]
epoch 35  0.7606009536441563


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98859217 0.96941526 0.59361997]
epoch 36  0.8505424689400222


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98910938 0.96537716 0.5734767 ]
epoch 37  0.8426544134580837


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98990161 0.97130732 0.6272578 ]
epoch 38  0.8628222404101606


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98887494 0.95245326 0.47454175]
epoch 39  0.8052899839824739


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98743469 0.96140877 0.5477707 ]
epoch 40  0.8322047195275228


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98798087 0.96531145 0.60322108]
epoch 41  0.852171135731094


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98479927 0.95818555 0.50306748]
epoch 42  0.8153507695736986


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98854252 0.95902175 0.49357326]
epoch 43  0.813712512144193


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98731008 0.97077533 0.59834711]
epoch 44  0.8521441732983872


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98688977 0.94018243 0.44837758]
epoch 45  0.7918165936268663


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98843332 0.96524164 0.54202899]
epoch 46  0.831901313380631


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9903946  0.97069124 0.57142857]
epoch 47  0.844171471958629


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98687869 0.97539479 0.5505618 ]
epoch 48  0.8376117586664348


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.9878201  0.95901485 0.55153949]
epoch 49  0.8327914809009966


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98768515 0.96003709 0.4811784 ]
epoch 50  0.8096335459702081


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.97561189 0.94822937 0.54397394]
epoch 51  0.8226050673735426


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98433812 0.95953322 0.68214804]
epoch 52  0.8753397953024337


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98558334 0.9630732  0.56012658]
epoch 53  0.8362610405636134


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98757335 0.95515357 0.49156627]
epoch 54  0.8114310625196764


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98726115 0.96038213 0.5572843 ]
epoch 55  0.8349758587223725


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98608606 0.96493506 0.58483755]
epoch 56  0.8452862234517191


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98749677 0.96854996 0.5935085 ]
epoch 57  0.8498517418100198


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98860005 0.96639672 0.55910987]
epoch 58  0.8380355500306399


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98691235 0.95989505 0.53888889]
epoch 59  0.8285654295099546


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98703201 0.95970696 0.54593176]
epoch 60  0.8308902429739109


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.989199   0.96529444 0.50625   ]
epoch 61  0.8202478136952832


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98724028 0.96883117 0.60747664]
epoch 62  0.8545160278932044


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98705098 0.96493506 0.59495798]
epoch 63  0.8489813422778134


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98869032 0.97098359 0.58170915]
epoch 64  0.847127686270304


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98701299 0.96284541 0.57492355]
epoch 65  0.841593980477921


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98495435 0.95818489 0.592     ]
epoch 66  0.845046411740054


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98768633 0.96882851 0.57967033]
epoch 67  0.8453950550975048


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98569089 0.96310788 0.5497076 ]
epoch 68  0.832835457517905


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98797051 0.96843669 0.60458015]
epoch 69  0.853662449574555


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.99019311 0.96816828 0.59259259]
epoch 70  0.8503179953804141


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98584276 0.95685757 0.55947712]
epoch 71  0.8340591539918701


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98837814 0.97362154 0.54517134]
epoch 72  0.8357236753143811


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98881934 0.9710212  0.60244648]
epoch 73  0.8540956748139455


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.99066229 0.97496345 0.55147059]
epoch 74  0.8390321081794708


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98887643 0.96913523 0.60596546]
epoch 75  0.8546590423319694


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98557445 0.96004502 0.6036036 ]
epoch 76  0.849741023153831


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98803478 0.95909389 0.53485064]
epoch 77  0.8273264347396857


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98349633 0.96155958 0.4556962 ]
epoch 78  0.8002507058989602


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98731337 0.96222367 0.51586207]
epoch 79  0.8217997035201571


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98936446 0.96683957 0.52449568]
epoch 80  0.8268999030608738


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98791645 0.95967063 0.49934297]
epoch 81  0.815643349510415


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98153496 0.96985703 0.5044586 ]
epoch 82  0.8186168618516826


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98796117 0.96022357 0.50140845]
epoch 83  0.8165310611739164


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98720875 0.96492537 0.57268722]
epoch 84  0.8416071164191609


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98822921 0.95615196 0.52071006]
epoch 85  0.8216970741372999


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98738754 0.96504277 0.57819905]
epoch 86  0.843543120489458


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.99115273 0.97669256 0.67817896]
epoch 87  0.882008087244068


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98968182 0.97077321 0.58294574]
epoch 88  0.8478002571748867


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98744697 0.97216552 0.55405405]
epoch 89  0.8378888502341194


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98623873 0.96415604 0.61318052]
epoch 90  0.8545250944555298


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.99023083 0.97354497 0.58625526]
epoch 91  0.8500103540315832


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98743437 0.95902025 0.56323338]
epoch 92  0.8365626686269282


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98948276 0.96086548 0.5443038 ]
epoch 93  0.8315506770531996


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.99002117 0.96720089 0.53585927]
epoch 94  0.8310271103416399


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98698733 0.95985677 0.59197787]
epoch 95  0.8462739889370857


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98592396 0.96347075 0.64573991]
epoch 96  0.8650448712554345


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98527397 0.95034785 0.58670143]
epoch 97  0.8407744192366841


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98775405 0.94703813 0.46506024]
epoch 98  0.799950806488341


Step ...:   0%|          | 0/244 [00:00<?, ?it/s]

Step ...:   0%|          | 0/68 [00:00<?, ?it/s]

[0.98800671 0.95584906 0.52047556]
epoch 99  0.8214437746527755


### evaluate_model(model, test_dataset)

In [2]:
random.randint(0, 256)

22

In [3]:
random.randint(0, 256)

39

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [6]:
random.randint(0, 256)

171