In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_npu_model, evaluate_model
from models.conv_mlp import CONV_NPU
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 42
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = CONV_NPU()

In [9]:
sum(p.numel() for p in model.parameters())

245283

In [ ]:
train_npu_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98417168 0.87985655 0.17672791]
epoch 0  0.6802520446063509


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9868404  0.93425995 0.32201258]
epoch 1  0.7477043118867527


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97423496 0.93729432 0.62875197]
epoch 2  0.8467604180847662


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97929731 0.9358233  0.52978454]
epoch 3  0.8149683831344875


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99008877 0.96120173 0.54351687]
epoch 4  0.8316024588649128


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99053382 0.96566958 0.57419355]
epoch 5  0.8434656509409316


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98923435 0.97318861 0.66558966]
epoch 6  0.8760042049869323


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98786189 0.95918751 0.56035768]
epoch 7  0.8358023594508968


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98726579 0.96517506 0.67642276]
epoch 8  0.8762878714042862


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98685506 0.959842   0.60759494]
epoch 9  0.8514306670603858


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

### evaluate_model(model, test_dataset)

In [2]:
random.randint(0, 256)

22

In [3]:
random.randint(0, 256)

39

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [6]:
random.randint(0, 256)

171