In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_model, train_fft_model, evaluate_model
from models.conv_mlp import CONV_MLP
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 29
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = CONV_MLP(frame_size=32)

In [9]:
train_fft_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.1428691792468329
15.756957061114496


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97918614 0.81520816 0.17930205]
epoch 0  0.657898779158414


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.06030053887452614
2.396577652964504


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98876597 0.83366275 0.16498516]
epoch 1  0.6624712945366351


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.04734949690954836
2.1889735250380005


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99207033 0.95090199 0.39879154]
epoch 2  0.7805879544813273


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.04034259766792538
1.9958874759488037


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99190144 0.96740235 0.57885615]
epoch 3  0.8460533122845145


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0367663570571922
1.84414485204024


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9894782  0.9539567  0.56992084]
epoch 4  0.8377852492256083


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.03225758910212375
1.6602382781997598


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98859349 0.97140271 0.74463938]
epoch 5  0.901545192286593


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.026360130084234608
1.5416267503213588


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9897696  0.96901719 0.63465553]
epoch 6  0.8644807752333339


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.026201551898853457
1.5098167420106747


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99232759 0.95955161 0.4951049 ]
epoch 7  0.8156613642361119


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.02393355633330056
1.4707640644155244


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9893156  0.96682464 0.66064982]
epoch 8  0.8722633538518704


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.021208594059920184
1.4008504572406686


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99190423 0.96464222 0.5832106 ]
epoch 9  0.8465856855552764


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.02124249342770732
1.4013504304251876


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99166847 0.97241252 0.65849923]
epoch 10  0.8741934052870465


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.020563869964586548
1.370040643049951


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99034924 0.97270883 0.58170915]
epoch 11  0.8482557409980916


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.019978460131519372
1.3643783790650308


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99305106 0.95435763 0.47820672]
epoch 12  0.8085384700776013


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.018262943246838508
1.329116767803991


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99283927 0.97015482 0.62290503]
epoch 13  0.8619663738811342


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01853671395675609
1.344879478491552


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98527639 0.96079332 0.61876248]
epoch 14  0.8549440603982288


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01767733519299116
1.3087991182319438


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98979945 0.97434473 0.65502183]
epoch 15  0.8730553353991569


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.016307885033353866
1.2814066194349736


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99121976 0.97639981 0.72289157]
epoch 16  0.8968370484347772


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.015415969381036437
1.2661799060857761


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98960838 0.95781591 0.59770115]
epoch 17  0.8483751460485388


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.014239593828891907
1.2533817451592588


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99075865 0.97412028 0.71451876]
epoch 18  0.8931325620275926


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.013113560849598431
1.232355690253344


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98905532 0.96758059 0.63238095]
epoch 19  0.8630056206819323


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.013320545879854949
1.1956918420732878


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98782429 0.96538786 0.6452514 ]
epoch 20  0.866154516711445


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.014359285737061217
1.2489056387109188


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99118181 0.97541735 0.69863014]
epoch 21  0.8884097673075343


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01186167731896055
1.1898315237869472


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98909778 0.96870926 0.68493151]
epoch 22  0.8809128467757842


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.01265297990263708
1.2463009453529694


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99010838 0.97070896 0.70987654]
epoch 23  0.8902312920692373


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.010525781094889145
1.1846181236253381


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98366668 0.95562689 0.68048359]
epoch 24  0.8732590538333759


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.011630518774899236
1.1905155782520893


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98745236 0.96789204 0.67557252]
epoch 25  0.8769723064651095


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.010233889766957804
1.194353616259059


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99174832 0.97182054 0.66666667]
epoch 26  0.8767451772957288


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.009420024280190923
1.1619888370898714


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99172057 0.97813706 0.72426471]
epoch 27  0.8980407772877944


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.009905878671545583
1.2096254022398034


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99101964 0.96979897 0.7208589 ]
epoch 28  0.8938925012253858


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007798897165452287
1.1142710020624147


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99173767 0.97760089 0.7716263 ]
epoch 29  0.9136549523978922


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00823414669309223
1.1126393876373155


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99035979 0.96596222 0.62028986]
epoch 30  0.8588706211390716


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008420835656015369
1.1483639629530955


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99007775 0.96516008 0.65368567]
epoch 31  0.8696411652262824


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008742482025488099
1.1214255760490772


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99356344 0.97920674 0.6967509 ]
epoch 32  0.8898403603904921


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008524433195842432
1.172889892784477


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99301905 0.97891622 0.74333333]
epoch 33  0.905089533282253


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008493773241944315
1.119917142287172


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99160388 0.97581687 0.67736185]
epoch 34  0.8815942005916075


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008022359978669897
1.113338728062426


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98909563 0.97018222 0.66770186]
epoch 35  0.8756599042398993


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0075725770306013795
1.0932755206216287


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98905455 0.97108209 0.65994236]
epoch 36  0.873359669173711


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006658902784749639
1.1008822932778197


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98859348 0.97201302 0.76697248]
epoch 37  0.9091929920850768


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008633104537457126
1.115862692727323


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98957037 0.97140196 0.7440273 ]
epoch 38  0.9016665425997301


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0060348009318853466
1.0505456927345274


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98897043 0.96844865 0.69278997]
epoch 39  0.8834030154120281


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00792019003681791
1.1203908540415568


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9902921  0.96247407 0.65395095]
epoch 40  0.8689057070596041


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007888240111025182
1.1030781922796913


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99210697 0.97163121 0.65646732]
epoch 41  0.8734018290335402


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.00580869631846296
1.0346034978357674


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98714742 0.97010519 0.74496644]
epoch 42  0.9007396816520195


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0067426779504809135
1.101305493415626


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98932018 0.96948137 0.76404494]
epoch 43  0.9076154981638759


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006412544754602324
1.0593298548943453


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99212259 0.97698919 0.76056338]
epoch 44  0.9098917209269842


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006293522051626768
1.0411338190676251


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98934982 0.97040873 0.68461538]
epoch 45  0.881457979322915


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005856911312212316
1.0443461783979953


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98973588 0.97314936 0.76847291]
epoch 46  0.9104527148586784


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004661263562849931
1.0067990546935148


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99089034 0.96460177 0.67217631]
epoch 47  0.8758894729248615


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006728371583576849
1.1116766980571913


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98982352 0.97076023 0.70967742]
epoch 48  0.8900870583691033


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0072895358896820145
1.0573770014810122


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97914408 0.92717484 0.47628866]
epoch 49  0.7942025268184141


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0062951513575946055
1.0451933255981372


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98841401 0.97143924 0.75083056]
epoch 50  0.9035612697809801


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005705273471490278
0.985462219563353


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98764156 0.96987839 0.65346535]
epoch 51  0.8703284332662083


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005452416984095761
1.0310116759530084


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98830409 0.96468401 0.55629139]
epoch 52  0.8364264997218722


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005991625688855448
1.0735651549923346


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99072916 0.97436374 0.6907994 ]
epoch 53  0.8852974321831558


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005904220287529029
1.044153646338402


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98834918 0.96817326 0.73088685]
epoch 54  0.8958030966764564


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004093357046826274
1.011502479946956


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99288824 0.97853839 0.70607553]
epoch 55  0.8925007205389951


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005159134824171674
1.0147143605125024


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98944931 0.97241059 0.74953618]
epoch 56  0.9037986910601159


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.008343746762663065
1.1102129008001371


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99084225 0.9719661  0.70192308]
epoch 57  0.8882438100239872


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004688863121807618
1.033954118678702


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99109563 0.97728748 0.75767918]
epoch 58  0.9086874272648303


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0042042132970676145
0.9761642825615724


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98943934 0.97465051 0.77852349]
epoch 59  0.9142044477057212


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004791941411101334
1.0060509580820494


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9925734  0.97970854 0.69255663]
epoch 60  0.8882795258605963


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005827568141345538
1.0193110230614029


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99021291 0.97175878 0.70588235]
epoch 61  0.8892846832105225


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005122380007395765
1.0232179702185018


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98873796 0.96930804 0.66225166]
epoch 62  0.8734325518600045


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003707319077038855
0.9596165715883155


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99082806 0.97322425 0.67394696]
epoch 63  0.8793330877335497


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.007555951926901405
1.1392076532423374


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98909965 0.96769965 0.65934066]
epoch 64  0.8720466536766743


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0041869534064580514
0.9952814968673845


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99003466 0.96323597 0.58515284]
epoch 65  0.8461411573645861


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005297126222225611
1.039930249279407


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98850377 0.96741667 0.67001675]
epoch 66  0.8753123999151603


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004236540661921319
0.9577024244307493


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99053519 0.97352722 0.6882716 ]
epoch 67  0.8841113384364689


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003997690419438932
1.0164178802461594


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99291821 0.98024007 0.72151899]
epoch 68  0.8982257584062578


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005298052269340503
1.0096472876119662


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9870364  0.96157451 0.64220183]
epoch 69  0.8636042479758489


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005296469121876953
0.9913624186504792


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98834419 0.9694635  0.73946958]
epoch 70  0.8990924217176447


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005548687994001858
1.01712443782074


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98944478 0.96463563 0.57621441]
epoch 71  0.8434316030567834


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0038475029673663906
0.9382225200686857


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98893843 0.96429239 0.60869565]
epoch 72  0.8539754919303056


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004067290758811796
0.9521842998676231


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99177681 0.96477167 0.53996983]
epoch 73  0.8321727712589452


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006897047572205533
1.1269659373519112


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98944387 0.96816602 0.64767616]
epoch 74  0.8684286863981711


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003768861673958588
0.9666410332863091


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98639165 0.93765151 0.51757188]
epoch 75  0.8138716798286816


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0037529628547490717
0.9386631543968003


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9902946  0.97796783 0.7694974 ]
epoch 76  0.9125866109523751


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005470349297794353
1.0057289285367275


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9885445  0.97565942 0.61290323]
epoch 77  0.8590357154220535


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004271894814688882
0.9521641606728889


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99050402 0.97225326 0.65897858]
epoch 78  0.8739119531908428


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0037476296834745883
0.9236860304183538


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98922793 0.96979332 0.67412141]
epoch 79  0.8777142195390173


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0034129786383152202
0.9427212905253473


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99070168 0.97767071 0.67671692]
epoch 80  0.8816964364284429


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005450093220541424
1.0227123373465372


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99117876 0.97421203 0.64296296]
epoch 81  0.8694512523947765


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003964115423615102
0.9718018850384307


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98756432 0.95179918 0.55407047]
epoch 82  0.831144658500128


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004938533053055161
1.0127245696601928


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9899146  0.97438277 0.68990826]
epoch 83  0.8847352087213521


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003662640616165254
0.9271733770778047


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9887168  0.97468826 0.73982301]
epoch 84  0.9010760232041912


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004140162760486163
0.9496161769272365


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98949715 0.96606377 0.61022928]
epoch 85  0.8552633987999972


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003510631241320573
0.9353563837263373


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99012282 0.97321429 0.68041237]
epoch 86  0.8812498258090651


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003852512930686337
0.9228235838257801


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99097395 0.97356258 0.6641791 ]
epoch 87  0.8762385462565772


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003511393567956169
0.9224673304745059


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9912737  0.9767184  0.67542214]
epoch 88  0.8811380796040829


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.006011348269727621
0.9865113518045913


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98765855 0.96902199 0.7278798 ]
epoch 89  0.8948534488076878


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0038590614465736366
1.0716238307787653


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99148314 0.97663638 0.68259386]
epoch 90  0.8835711251610009


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.003958297489462754
0.915934055783543


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99075786 0.97700619 0.75378788]
epoch 91  0.9071839739002168


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004667090734453997
0.9718115579727005


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98709871 0.96913753 0.71985816]
epoch 92  0.892031465012295


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0032925867721461154
0.9614760301685921


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98898178 0.97036759 0.68779715]
epoch 93  0.882382172829979


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.004161510677676155
0.9537462990050198


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98991633 0.97690015 0.75993092]
epoch 94  0.908915797123696


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.002065223416648043
0.8808857790008953


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9902921  0.9763677  0.72635135]
epoch 95  0.8976703812956254


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.005834056251543268
1.0202412606203581


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98738306 0.97035241 0.70945946]
epoch 96  0.8890649771336777


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0035458925868386134
0.8856694401075463


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99019776 0.97632698 0.70695971]
epoch 97  0.8911614849673235


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0029359706277461302
0.8896983288672181


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99162551 0.97712751 0.72014925]
epoch 98  0.8963007585076536


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

0.0034215472502033867
0.8717220754685833


Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98794354 0.95724872 0.59212198]
epoch 99  0.8457714119830356


### evaluate_model(model, test_dataset)

In [ ]:
random.randint(0, 256)

In [ ]:
random.randint(0, 256)

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [6]:
random.randint(0, 256)

171