In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_model, evaluate_model
from models.conv_mlp import GRU
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 42
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = GRU()

In [9]:
sum(p.numel() for p in model.parameters())

15903

In [10]:
train_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98509248 0.92669406 0.36729223]
epoch 0  0.7596929226319499


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98652406 0.95383178 0.60917431]
epoch 1  0.8498433839328876


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98848698 0.96453901 0.70927835]
epoch 2  0.8874347803418271


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98831213 0.96504657 0.73663366]
epoch 3  0.8966641239823264


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98534    0.95458793 0.63339731]
epoch 4  0.8577750804016281


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99092716 0.97160709 0.67005076]
epoch 5  0.8775283376979521


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9885997  0.96736015 0.65714286]
epoch 6  0.8710342346484999


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9890053  0.97139694 0.68251273]
epoch 7  0.8809716578249959


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99144487 0.97578361 0.75422139]
epoch 8  0.9071499537486761


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98974557 0.96863144 0.72727273]
epoch 9  0.8952165799522223


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99053438 0.97093292 0.72828096]
epoch 10  0.8965827512055208


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.95662141 0.90185121 0.66528926]
epoch 11  0.8412539561290892


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98339928 0.95634518 0.73545966]
epoch 12  0.891734705811804


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98757391 0.9650116  0.74556213]
epoch 13  0.8993825482980866


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99069447 0.97200221 0.69454545]
epoch 14  0.8857473777585646


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98577793 0.96154204 0.73743017]
epoch 15  0.894916713569211


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98714212 0.96376812 0.73282443]
epoch 16  0.8945782219433132


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9884475  0.96329337 0.69686411]
epoch 17  0.8828683280365018


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98815451 0.95706089 0.57587549]
epoch 18  0.840363628305358


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9882546  0.96954596 0.64536741]
epoch 19  0.8677226563004528


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98887218 0.96566524 0.70175439]
epoch 20  0.885430600822514


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98783371 0.96594832 0.659375  ]
epoch 21  0.871052343052081


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98811881 0.96488777 0.65237366]
epoch 22  0.8684600810566939


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98866233 0.96664196 0.63074485]
epoch 23  0.8620163778251867


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98748871 0.9668115  0.65808824]
epoch 24  0.8707961499187684


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98514077 0.96604258 0.57909605]
epoch 25  0.8434264670898389


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9890668  0.97070511 0.68430335]
epoch 26  0.8813584219370493


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98119879 0.94942276 0.68992248]
epoch 27  0.8735146776537578


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98015201 0.95644267 0.69899666]
epoch 28  0.8785304434620972


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98795388 0.96898435 0.7026087 ]
epoch 29  0.8865156431747082


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98684725 0.96662726 0.67918089]
epoch 30  0.8775517983625584


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98543001 0.96428571 0.62385321]
epoch 31  0.8578563111536536


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98784312 0.96602302 0.69244288]
epoch 32  0.8821030084366104


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98937406 0.96806846 0.70866142]
epoch 33  0.888701313472594


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98764479 0.96185924 0.67292645]
epoch 34  0.8741434933003235


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99010414 0.9754893  0.7266055 ]
epoch 35  0.8973996493932779


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99098477 0.97435426 0.73476703]
epoch 36  0.9000353529722571


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98566232 0.96002252 0.71452421]
epoch 37  0.8867363483210897


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98855323 0.96497765 0.66873065]
epoch 38  0.8740871757452844


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98909122 0.97130161 0.76779026]
epoch 39  0.9093943648082373


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.96768768 0.93523658 0.62444772]
epoch 40  0.8424573263353893


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98675241 0.9627972  0.68070175]
epoch 41  0.8767504562529101


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98688905 0.9635844  0.75294118]
epoch 42  0.9011382096568893


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98975904 0.97147589 0.73046875]
epoch 43  0.8972345595577008


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98774457 0.96940389 0.67647059]
epoch 44  0.8778730155275166


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98762887 0.96649652 0.72212389]
epoch 45  0.8920830931687563


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98635193 0.96621496 0.72527473]
epoch 46  0.8926138728502071


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98780278 0.96368353 0.6900369 ]
epoch 47  0.8805077370939459


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98167733 0.97099715 0.54219949]
epoch 48  0.8316246545817721


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.99019439 0.97229405 0.75555556]
epoch 49  0.906014666630806


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98532369 0.95976958 0.70781893]
epoch 50  0.8843040675892464


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98727757 0.96906262 0.70250896]
epoch 51  0.8862830495934597


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98933884 0.96881343 0.72692308]
epoch 52  0.8950251156685635


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98954794 0.97388266 0.72434608]
epoch 53  0.8959255566269521


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98187092 0.95623529 0.75724638]
epoch 54  0.8984508639621521


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98801701 0.97054465 0.71349353]
epoch 55  0.8906850615939442


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98930734 0.9672619  0.71944923]
epoch 56  0.8920061563646057


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98736136 0.96485208 0.6573913 ]
epoch 57  0.8698682494021542


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9864494  0.96625222 0.72305141]
epoch 58  0.8919176765080629


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98573448 0.96657667 0.7238806 ]
epoch 59  0.8920639157610251


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98856724 0.97312771 0.66013072]
epoch 60  0.8739418897211683


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98928064 0.97307799 0.69415808]
epoch 61  0.8855055689144603


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98744194 0.96939343 0.67576792]
epoch 62  0.8775344306890845


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9827542  0.95927177 0.74349442]
epoch 63  0.8951734667644603


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98785843 0.97224527 0.7140255 ]
epoch 64  0.8913764032479184


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98737764 0.96751439 0.7400722 ]
epoch 65  0.8983214096812002


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98813618 0.97217343 0.7458256 ]
epoch 66  0.9020450699151342


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98841997 0.96512495 0.70344828]
epoch 67  0.885664399452531


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98826564 0.96824513 0.73162393]
epoch 68  0.8960448973487556


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98789076 0.96697982 0.72633391]
epoch 69  0.8937348273590553


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98891276 0.97012044 0.70613108]
epoch 70  0.888388093019736


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98723441 0.96585004 0.748     ]
epoch 71  0.9003614814158983


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98578362 0.96414566 0.67942584]
epoch 72  0.8764517048444423


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98782057 0.96543416 0.71624266]
epoch 73  0.8898324624481826


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9880461  0.96837294 0.64150943]
epoch 74  0.865976157640246


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98706656 0.96687139 0.6422629 ]
epoch 75  0.8654002823318523


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98667695 0.96303863 0.70333988]
epoch 76  0.8843518210766423


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98809882 0.96682464 0.64383562]
epoch 77  0.8662530264876258


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98791242 0.96416207 0.62973761]
epoch 78  0.860604031399248


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98801701 0.96524311 0.6628131 ]
epoch 79  0.8720244078555357


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98784902 0.97181282 0.61510791]
epoch 80  0.8582565845505226


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98641293 0.96227639 0.62      ]
epoch 81  0.8562297732097005


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98705751 0.96372768 0.68913858]
epoch 82  0.8799745893309835


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98755365 0.96184479 0.59770115]
epoch 83  0.8490331945218171


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9880829  0.95910711 0.53884712]
epoch 84  0.8286790429030786


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98697738 0.96300428 0.65250965]
epoch 85  0.867497103388566


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98755685 0.96725581 0.70212766]
epoch 86  0.8856467752802217


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98506824 0.95903796 0.67993367]
epoch 87  0.8746799539323306


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98683251 0.96254891 0.70052539]
epoch 88  0.8833022717699901


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98686647 0.9673853  0.61141805]
epoch 89  0.8552232707376058


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98851069 0.97046023 0.68041237]
epoch 90  0.8797944307213658


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98738197 0.96781994 0.68661972]
epoch 91  0.8806072110116588


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98854732 0.96661721 0.66885246]
epoch 92  0.8746723291200427


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98652129 0.96762223 0.67155963]
epoch 93  0.8752343842144673


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98929999 0.96955677 0.64206642]
epoch 94  0.8669743921778711


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98323927 0.96155645 0.75415896]
epoch 95  0.8996515607434857


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98653863 0.96856162 0.70450098]
epoch 96  0.8865337432262583


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98549112 0.96518987 0.78669276]
epoch 97  0.9124579173028661


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98701855 0.96777809 0.77272727]
epoch 98  0.9091746376251247


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98842295 0.96557484 0.68330134]
epoch 99  0.8790997090522064


### evaluate_model(model, test_dataset)

In [2]:
random.randint(0, 256)

22

In [3]:
random.randint(0, 256)

39

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [6]:
random.randint(0, 256)

171