In [1]:
import pandas as pd
import numpy as np
from pqd_dataset import PQDDataset
from sklearn.utils.class_weight import compute_class_weight
import torch
from torch.utils.data import DataLoader
from pqd_trainer import train_model, evaluate_model
from models.conv_mlp import MLP
import random
import os

In [2]:
def seed_everything(seed: int = 42):
    """
    This function is used to maintain repeatability
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
seed = 42
seed_everything(seed)

In [4]:
window_size = 32
stride = 1
target_mode = True
epochs=100
batch_size=32
lr = 0.0005

In [5]:
train_df = pd.read_csv('train.csv')
train_dataset = PQDDataset(
                            df=train_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/66 [00:00<?, ?it/s]

In [6]:
weights = compute_class_weight("balanced", classes=np.unique(train_dataset.df.target), y=train_dataset.df.target)
weights = torch.FloatTensor(weights)

In [7]:
test_df = pd.read_csv('test.csv')
test_dataset = PQDDataset(
                            df=test_df,
                            window_size=window_size,
                            stride=stride,
                            target_mode=target_mode
                            )

Creating window slices:   0%|          | 0/13 [00:00<?, ?it/s]

In [8]:
model = MLP(32)

In [9]:
sum(p.numel() for p in model.parameters())

15847

In [10]:
train_model(
            model=model,
            dataset=train_dataset,
            run_seed=seed,
            eval_dataset=test_dataset,
            epochs=epochs,
            batch_size=batch_size,
            lr=lr,
            weights=None)

Epoch ...:   0%|          | 0/100 [00:00<?, ?it/s]

Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97212131 0.92108496 0.33972603]
epoch 0  0.7443107685111819


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97850607 0.93236074 0.4745167 ]
epoch 1  0.7951278345945432


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97701444 0.93031456 0.38443936]
epoch 2  0.7639227862640058


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.982247   0.90649976 0.31912568]
epoch 3  0.7359574802043397


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98094869 0.93967026 0.45490196]
epoch 4  0.7918403047985262


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97976406 0.94729981 0.58103976]
epoch 5  0.8360345422178952


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98101239 0.92738805 0.39669421]
epoch 6  0.7683648848218585


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98294989 0.95075303 0.53650794]
epoch 7  0.8234036160281065


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98231072 0.89106732 0.36587367]
epoch 8  0.7464172344176921


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98265946 0.94444444 0.42222222]
epoch 9  0.7831087074713136


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98286544 0.95020669 0.61780105]
epoch 10  0.8502910603120398


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97702936 0.92908855 0.5393586 ]
epoch 11  0.8151588360170368


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98068633 0.94533284 0.64670659]
epoch 12  0.857575249846963


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98609084 0.95398887 0.57142857]
epoch 13  0.8371694261819247


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98369495 0.95052474 0.57487091]
epoch 14  0.8363635347581327


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98172256 0.95576692 0.61045531]
epoch 15  0.8493149321387826


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98292871 0.94925985 0.59115044]
epoch 16  0.8411130000971845


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98566324 0.95784242 0.64272212]
epoch 17  0.8620759230897481


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98224343 0.95437685 0.65164645]
epoch 18  0.8627555781298383


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9811141  0.94467612 0.58681023]
epoch 19  0.8375334809709281


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98306251 0.95280318 0.62900188]
epoch 20  0.8549558552849407


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98297982 0.94749764 0.62229102]
epoch 21  0.850922825404155


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98205855 0.95039701 0.62884927]
epoch 22  0.8537682757350241


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98418172 0.95473781 0.5136612 ]
epoch 23  0.8175269096595682


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98486144 0.95434986 0.61538462]
epoch 24  0.8515319729295882


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98217347 0.95143632 0.60971524]
epoch 25  0.8477750110923647


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98512708 0.95083497 0.56491228]
epoch 26  0.8336247769290185


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97817837 0.94393814 0.59050967]
epoch 27  0.8375420576126739


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98469978 0.95706552 0.62827225]
epoch 28  0.8566791848271986


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98451906 0.95346681 0.59649123]
epoch 29  0.8448257015863727


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98006602 0.94630936 0.66261398]
epoch 30  0.8629964518607989


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98442261 0.9572028  0.68581081]
epoch 31  0.8758120715149853


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9855557  0.95488228 0.62420382]
epoch 32  0.8548806004316436


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98481729 0.95712413 0.65916399]
epoch 33  0.8670351380138901


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98116623 0.94632977 0.61431065]
epoch 34  0.8472688806142067


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98535081 0.95983522 0.68128162]
epoch 35  0.8754892166229182


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98391675 0.9526272  0.56238361]
epoch 36  0.8329758542990456


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98371111 0.94992609 0.60677966]
epoch 37  0.8468056201276131


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98224291 0.95360682 0.62035541]
epoch 38  0.8520683791648659


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9793447  0.94033056 0.60897436]
epoch 39  0.842883206937036


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98460749 0.95466816 0.61349693]
epoch 40  0.8509241931816458


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98346507 0.95508052 0.67785235]
epoch 41  0.8721326455384397


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98334832 0.95744084 0.68309859]
epoch 42  0.8746292484020302


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98578689 0.96275124 0.71223022]
epoch 43  0.8869227833360475


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98620956 0.95669145 0.60034305]
epoch 44  0.8477480220251317


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9845744  0.95336596 0.58301158]
epoch 45  0.8403173147665539


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98646035 0.95711229 0.59735974]
epoch 46  0.8469774578837924


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98434619 0.95716148 0.67964602]
epoch 47  0.8737178951570334


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98054077 0.94514047 0.68113523]
epoch 48  0.8689388222824085


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98187865 0.94989562 0.6963434 ]
epoch 49  0.8760392230036675


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98610754 0.95590301 0.58995138]
epoch 50  0.8439873069724312


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98493667 0.95708155 0.64794007]
epoch 51  0.86331942849875


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98496981 0.9575644  0.625     ]
epoch 52  0.8558447379898233


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98191589 0.94817219 0.68292683]
epoch 53  0.871004969266506


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97902038 0.94321408 0.66306306]
epoch 54  0.8617658432722077


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98598912 0.95750814 0.59315589]
epoch 55  0.8455510487385604


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9822669  0.95491351 0.67478261]
epoch 56  0.8706543395911407


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98393057 0.95304251 0.62659381]
epoch 57  0.8545222950092223


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98574059 0.95915139 0.65769231]
epoch 58  0.8675280962840909


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98313479 0.95294449 0.64855072]
epoch 59  0.861543336535015


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9831045  0.95569265 0.67034991]
epoch 60  0.8697156854128923


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.984894   0.95583302 0.67576792]
epoch 61  0.872164980446486


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98263874 0.94679142 0.62751678]
epoch 62  0.8523156459598208


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98309043 0.95536285 0.66420664]
epoch 63  0.8675533065078573


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98285322 0.95463879 0.72318339]
epoch 64  0.8868918016550559


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98620276 0.96281837 0.71374046]
epoch 65  0.8875871950632402


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98320807 0.95719844 0.65064695]
epoch 66  0.8636844891798282


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98544645 0.95911128 0.65934066]
epoch 67  0.8679661293051805


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97640622 0.93824588 0.64564565]
epoch 68  0.8534325829443912


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98585391 0.95788094 0.67105263]
epoch 69  0.8715958281702781


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98205238 0.95088336 0.62427746]
epoch 70  0.8524043997285338


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9817637  0.94545455 0.62285714]
epoch 71  0.8500251289806084


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98371864 0.95537221 0.66907776]
epoch 72  0.869389537650299


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98461011 0.9583372  0.69767442]
epoch 73  0.8802072422181281


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98360937 0.95443109 0.60377358]
epoch 74  0.8472713477955285


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.97995258 0.95119934 0.70955882]
epoch 75  0.8802369126039093


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98424994 0.95574405 0.67164179]
epoch 76  0.8705452598674892


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98581773 0.95576545 0.6462585 ]
epoch 77  0.8626138958055244


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98009307 0.94716566 0.6627451 ]
epoch 78  0.8633346090238038


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98200803 0.95621781 0.64098074]
epoch 79  0.8597355226534141


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98169219 0.95323065 0.74410774]
epoch 80  0.8930101956631219


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98638349 0.95816212 0.63799283]
epoch 81  0.860846147409717


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9876373  0.96228869 0.67918623]
epoch 82  0.8763707395185235


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98519596 0.95968645 0.68045113]
epoch 83  0.8751111796554905


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98797457 0.96337609 0.66435986]
epoch 84  0.8719035095391557


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98621339 0.95932077 0.63003663]
epoch 85  0.8585235971803366


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98397915 0.95225564 0.68062827]
epoch 86  0.8722876876283062


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98409423 0.9537037  0.58781362]
epoch 87  0.8418705182366532


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98446261 0.95562821 0.64130435]
epoch 88  0.8604650569214999


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98593361 0.9605422  0.70056497]
epoch 89  0.8823469273026635


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98394898 0.95604396 0.65510597]
epoch 90  0.8650329694080261


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98334974 0.95737273 0.64444444]
epoch 91  0.8617223051090214


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98248612 0.95353649 0.64705882]
epoch 92  0.8610271447258747


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98607649 0.96141064 0.68339768]
epoch 93  0.8769616039639475


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98199983 0.94984704 0.65793781]
epoch 94  0.863261557574981


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98022148 0.948584   0.65338645]
epoch 95  0.8607306456268167


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.9845798  0.92532405 0.42735043]
epoch 96  0.7790847580307698


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98421549 0.95935719 0.62354892]
epoch 97  0.8557072014887744


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98157137 0.9522929  0.64      ]
epoch 98  0.8579547575830211


Step ...:   0%|          | 0/1948 [00:00<?, ?it/s]

Step ...:   0%|          | 0/541 [00:00<?, ?it/s]

[0.98663354 0.96259073 0.69172932]
epoch 99  0.8803178636194602


### evaluate_model(model, test_dataset)

In [2]:
random.randint(0, 256)

22

In [3]:
random.randint(0, 256)

39

In [4]:
random.randint(0, 256)

108

In [5]:
random.randint(0, 256)

182

In [6]:
random.randint(0, 256)

171